// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkrppudvqrsjaoagbimd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrcnBwdWR2cXJzamFvYWdiaW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzUyNDksImV4cCI6MjA3MDMxMTI0OX0.qhZoyp51h-yzbBIxiD-GJgDeQhRmJpr6bMPGnJfa7s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});